#!/bin/bash
# ============================================================
# SAFER Benchmark — Full Pipeline Runner v2 (post-review, round 2)
# Run from: code/v1/
#
# Usage:
#   bash run_pipeline.sh [model_key|all|baselines] [--legacy-single-source]
#
# CHANGES vs v1:
#   - Stage 1 now calls build_benchmark_multi.py (OpenI + ReXGradient-160K)
#     by DEFAULT instead of the old single-source build_benchmark.py.
#     Previously this script still called the 500-sample single-source
#     builder even after the multi-source pipeline was written, meaning
#     the "current" benchmark was never actually produced by the
#     documented pipeline unless someone manually edited this file.
#   - Pass --legacy-single-source as a second argument to reproduce the
#     original 500-sample OpenI-only submission instead (calls
#     build_benchmark.py, reading config.yaml's dataset.legacy_single_source
#     block).
#   - Stage 1 now also runs extract_examples.py (previously written but
#     never wired into the pipeline, so the paper's requested example
#     figures were never actually generated by "running the pipeline").
#   - Added a dedicated baselines invocation before the requested model's
#     inference stage, since `python run_inference.py --model baselines`
#     is a real, distinct mode (constant/random/text-only/shuffled-image)
#     that v1 never actually called anywhere in this script — you had to
#     know to run it manually. Now: running `bash run_pipeline.sh all`
#     runs the real VLMs AND all baselines; running a single model key
#     runs just that model (baselines still available via
#     `bash run_pipeline.sh baselines`).
#   - Passes --model to compute_metrics.py and generate_figures.py
#     consistently; generate_figures.py itself doesn't take --model (it
#     always regenerates all figures from whatever metrics exist), so it's
#     called without arguments as before, but comment clarifies this is
#     intentional, not an oversight.
# ============================================================

set -e
MODEL=${1:-all}
LEGACY_FLAG=${2:-}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "============================================"
echo "  SAFER Benchmark Pipeline v2"
echo "  Model: $MODEL"
if [ "$LEGACY_FLAG" == "--legacy-single-source" ]; then
  echo "  Dataset: LEGACY single-source (500 OpenI samples)"
else
  echo "  Dataset: multi-source (OpenI + ReXGradient-160K), config-driven"
fi
echo "============================================"

echo ""
echo "[Stage 1] Data Preparation"
echo "--------------------------------------------"
cd "$SCRIPT_DIR/01_data_prep"
# NOTE: Run any dataset download scripts manually first if not already
# fetched (OpenI CSVs/images; ReXGradient requires huggingface-cli login
# with accepted gated-dataset terms — see build_benchmark_multi.py docstring)
if [ "$LEGACY_FLAG" == "--legacy-single-source" ]; then
  echo "  Using LEGACY single-source builder (build_benchmark.py) ..."
  python build_benchmark.py
else
  echo "  Using DEFAULT multi-source builder (build_benchmark_multi.py) ..."
  python build_benchmark_multi.py
fi

echo "  Extracting representative examples for paper figures ..."
python extract_examples.py

echo ""
echo "[Stage 2] Inference — $MODEL"
echo "--------------------------------------------"
cd "$SCRIPT_DIR/02_inference"
if [ "$MODEL" == "all" ]; then
  # Real VLMs first, then all baselines (constant/random/text-only/
  # shuffled-image — the last of which now covers all three VLMs by
  # default per config.yaml's inference.shuffled_image_baseline_models).
  
  python run_inference.py --model all   # llama excluded — see LOCAL_DIRS
  python run_inference.py --model baselines
elif [ "$MODEL" == "baselines" ]; then
  python run_inference.py --model baselines
else
  python run_inference.py --model "$MODEL"
fi

echo ""
echo "[Stage 3] Metrics"
echo "--------------------------------------------"
cd "$SCRIPT_DIR/03_metrics"
if [ "$MODEL" == "all" ] || [ "$MODEL" == "baselines" ]; then
  python compute_metrics.py --model all
else
  python compute_metrics.py --model "$MODEL"
fi

echo ""
echo "[Stage 4] Figures & Tables"
echo "--------------------------------------------"
cd "$SCRIPT_DIR/04_analysis"
# generate_figures.py always regenerates all figures from whatever metrics
# files currently exist in results/v1/metrics — it doesn't take --model.
python generate_figures.py

echo ""
echo "============================================"
echo "  Pipeline complete."
echo "  Results → ../../results/v1/"
echo "============================================"